apiVersion: v1
kind: Service
metadata:
  metadata:
  name: pedidos-service
  namespace: microservicios-app
  labels:
    app: pedidos
spec:
  type: ClusterIP
  selector:
    app: pedidos
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  sessionAffinity: None