# SERVICIO CON LOADBALANCER
# En GKE, el loadbalancer nos crea una IP publica automaticamente
apiVersion: v1
kind: Service
metadata:
  metadata:
  name: gateway
  namespace: microservicios-app
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
  - port: 80 #el puerto interno del servicio
    targetPort: 8080 # puerto del contenedor
    protocol: TCP
    name: http